# Generated by packamon: do not edit by hand
# Instead of modifying this file, you can modify a template. See ?init for details.

FROM openanalytics/r-ver:3.6.3

# System libraries (incl. system requirements for R packages)
RUN apt-get update && apt-get install --no-install-recommends -y \
    libssl-dev \
    pandoc pandoc-citeproc \
    libxml2-dev \
    libicu-dev \
    libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN R -e "cat(\"local(options(repos = c(CRAN = 'https://cloud.r-project.org')))\n\", file = R.home('etc/Rprofile.site'), append = TRUE)"

# install dependencies
RUN R -e "install.packages('remotes')" && \
    R -e "remotes::install_version('brew', version = '1.0-6', upgrade = FALSE)" && \
    R -e "remotes::install_version('brio', version = '1.1.2', upgrade = FALSE)" && \
    R -e "remotes::install_version('commonmark', version = '1.7', upgrade = FALSE)" && \
    R -e "remotes::install_version('crayon', version = '1.4.1', upgrade = FALSE)" && \
    R -e "remotes::install_version('curl', version = '4.3.2', upgrade = FALSE)" && \
    R -e "remotes::install_version('digest', version = '0.6.27', upgrade = FALSE)" && \
    R -e "remotes::install_version('evaluate', version = '0.14', upgrade = FALSE)" && \
    R -e "remotes::install_version('fansi', version = '0.5.0', upgrade = FALSE)" && \
    R -e "remotes::install_version('glue', version = '1.4.2', upgrade = FALSE)"
RUN R -e "remotes::install_version('jsonlite', version = '1.7.2', upgrade = FALSE)" && \
    R -e "remotes::install_version('lazyeval', version = '0.2.2', upgrade = FALSE)" && \
    R -e "remotes::install_version('magrittr', version = '2.0.1', upgrade = FALSE)" && \
    R -e "remotes::install_version('mime', version = '0.11', upgrade = FALSE)" && \
    R -e "remotes::install_version('pkgconfig', version = '2.0.3', upgrade = FALSE)" && \
    R -e "remotes::install_version('praise', version = '1.0.0', upgrade = FALSE)" && \
    R -e "remotes::install_version('ps', version = '1.6.0', upgrade = FALSE)" && \
    R -e "remotes::install_version('R6', version = '2.5.0', upgrade = FALSE)" && \
    R -e "remotes::install_version('Rcpp', version = '1.0.6', upgrade = FALSE)" && \
    R -e "remotes::install_version('rlang', version = '0.4.11', upgrade = FALSE)"
RUN R -e "remotes::install_version('rprojroot', version = '2.0.2', upgrade = FALSE)" && \
    R -e "remotes::install_version('rstudioapi', version = '0.13', upgrade = FALSE)" && \
    R -e "remotes::install_version('stringi', version = '1.6.2', upgrade = FALSE)" && \
    R -e "remotes::install_version('sys', version = '3.4', upgrade = FALSE)" && \
    R -e "remotes::install_version('utf8', version = '1.2.1', upgrade = FALSE)" && \
    R -e "remotes::install_version('withr', version = '2.4.2', upgrade = FALSE)" && \
    R -e "remotes::install_version('xfun', version = '0.24', upgrade = FALSE)" && \
    R -e "remotes::install_version('xml2', version = '1.3.2', upgrade = FALSE)" && \
    R -e "remotes::install_version('yaml', version = '2.2.1', upgrade = FALSE)" && \
    R -e "remotes::install_version('askpass', version = '1.1', upgrade = FALSE)"
RUN R -e "remotes::install_version('cli', version = '3.0.0', upgrade = FALSE)" && \
    R -e "remotes::install_version('desc', version = '1.3.0', upgrade = FALSE)" && \
    R -e "remotes::install_version('diffobj', version = '0.3.4', upgrade = FALSE)" && \
    R -e "remotes::install_version('ellipsis', version = '0.3.2', upgrade = FALSE)" && \
    R -e "remotes::install_version('highr', version = '0.9', upgrade = FALSE)" && \
    R -e "remotes::install_version('lifecycle', version = '1.0.0', upgrade = FALSE)" && \
    R -e "remotes::install_version('markdown', version = '1.1', upgrade = FALSE)" && \
    R -e "remotes::install_version('mockr', version = '0.1', upgrade = FALSE)" && \
    R -e "remotes::install_version('processx', version = '3.5.2', upgrade = FALSE)" && \
    R -e "remotes::install_version('purrr', version = '0.3.4', upgrade = FALSE)"
RUN R -e "remotes::install_version('rex', version = '1.2.0', upgrade = FALSE)" && \
    R -e "remotes::install_version('stringr', version = '1.4.0', upgrade = FALSE)" && \
    R -e "remotes::install_version('callr', version = '3.7.0', upgrade = FALSE)" && \
    R -e "remotes::install_version('knitr', version = '1.33', upgrade = FALSE)" && \
    R -e "remotes::install_version('openssl', version = '1.4.4', upgrade = FALSE)" && \
    R -e "remotes::install_version('pkgload', version = '1.2.1', upgrade = FALSE)" && \
    R -e "remotes::install_version('vctrs', version = '0.3.8', upgrade = FALSE)" && \
    R -e "remotes::install_version('httr', version = '1.4.2', upgrade = FALSE)" && \
    R -e "remotes::install_version('pillar', version = '1.6.1', upgrade = FALSE)" && \
    R -e "remotes::install_version('roxygen2', version = '7.1.1', upgrade = FALSE)"
RUN R -e "remotes::install_version('covr', version = '3.5.1', upgrade = FALSE)" && \
    R -e "remotes::install_version('tibble', version = '3.1.2', upgrade = FALSE)" && \
    R -e "remotes::install_version('rematch2', version = '2.1.2', upgrade = FALSE)" && \
    R -e "remotes::install_version('waldo', version = '0.2.5', upgrade = FALSE)" && \
    R -e "remotes::install_version('testthat', version = '3.0.4', upgrade = FALSE)"


