version: "3.9"
services:
  crane:
    image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/crane-snapshot:latest
    hostname: oa-crane
    ports:
      - "7070:7070"
    volumes:
      - ./application.yaml:/opt/crane/application.yml
      - ./repo:/opt/rdepot/repo
    depends_on:
      keycloak:
        condition: service_healthy
  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    restart: unless-stopped
    hostname: oa-crane-keycloak
    container_name: crane-keycloak
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8080:8080"
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=testpassword
      - KEYCLOAK_IMPORT=/opt/master/realm-export.json
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
     - ./realm-export.json:/opt/master/realm-export.json
